### ISSUE TITLE
Winbind authenticate user over ssh on extern one way trust AD  

### ISSUE THREAD

**Issue by DarthDensus** [avati/samba#1]
In our company we have 2 test Domains.

Domain A -> Trust -> Domain B (Windows Server 2016)

Client (Debian 11 Buster) joined Domain B

I setup winbind over smb.conf

[global]
  security = ads
  realm = Domain B
  #password server = 10.2.X.X    #IP des Domain Controllers
  workgroup = Domain B
  dns forwarder = 10.2.X.X
  allow trusted domains = yes
  #idmap uid = 10000-20000
  #idmap gid = 10000-20000
  idmap config * : range = 10000 - 19999
  idmap config intern.lokal : backend = rid
  idmap config intern.lokal : range = 1000000 - 1999999
  idmap config dmz.lokal :  backend = rid
  idmap config dmz.lokal : range = 10000000 - 19999999
  #kerberos method = secrets only
  winbind enum users = yes
  winbind enum groups = yes
  #winbind cache time = 10
  winbind offline logon = false
  #winbind use krb5 enterprise principals = Yes
  winbind nss info = rfc2307
  winbind use default domain = no
  winbind nested groups = yes
  template homedir = /home/%U
  template shell = /bin/bash
  load printers = no
  printcap name = /dev/null
  vfs objects = acl_xattr
  map acl inherit = yes
  store dos attributes = yes
  lanman auth = no
  ntlm auth = yes
  client lanman auth = no
  #client use spnego = yes
  #client ntlmv2 auth = yes
  encrypt passwords = yes
  restrict anonymous = 2
  domain master = no
  local master = no
  preferred master = no
  os level = 0

So if i searched the internet, i read that clients use ntm for one way trust and not kerberos.

I land up on an article for open suse https://www.suse.com/de-de/support/kb/doc/?id=000020245 

i could not find that file mentioned in the articel, so i created that file, but it does not work.
I think that it has no effect on debian.

my authlog:
Jul 10 16:26:45 sus-deb-02-lt sshd[14336]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=10.201.114.30  user=a-admin@Domain A
Jul 10 16:26:45 sus-deb-02-lt sshd[14336]: pam_winbind(sshd:auth): getting password (0x00000388)
Jul 10 16:26:45 sus-deb-02-lt sshd[14336]: pam_winbind(sshd:auth): pam_get_item returned a password
Jul 10 16:26:45 sus-deb-02-lt sshd[14336]: pam_winbind(sshd:auth): request wbcLogonUser failed: WBC_ERR_AUTH_ERROR, PAM error: PAM_AUTHINFO_UNAVAIL (9), NTSTATUS: NT_STATUS_NO_LOGON_SERVERS, Error message was: No logon servers are currently available to service the logon request.
Jul 10 16:26:45 sus-deb-02-lt sshd[14336]: pam_winbind(sshd:auth): internal module error (retval = PAM_AUTHINFO_UNAVAIL(9), user = 'Domain A\a-admin')
Jul 10 16:26:47 sus-deb-02-lt sshd[14336]: Failed password for a-admin@Domain A from 10.X.X.X port 56587 ssh2
Jul 10 16:26:49 sus-deb-02-lt sshd[14336]: Connection reset by authenticating user a-admin@Domain A 10.X.X.X port 56587 [preauth]

 wbinfo --online-status
BUILTIN : active connection
SUS-DEB-02-LT (My Client) : active connection
Domian B : active connection
Domain A : no active connection

wbinfo --trusted-domains --verbose
Domain Name     DNS Domain                                                       Trust Type  Transitive  In   Out
BUILTIN                                                                          Local
SUS-DEB-02-LT(My Client)                                            Local
Domain B             blablabla1.lokal                                                        Workstation Yes         No   No
Domain A          blablabla2.lokal

ssh with user from Domain B works.

Did you guys have a clue why this does not work as aspected? 

I would be happy about your assistance.

**Comment by avati** [comment]
This is not the official samba repo, just a private clone. Please refer to https://github.com/samba-team/samba instead.
